/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assessmnet2;


import java.awt.event.ActionListener;


/**
 *
 * @author Sarah
 */
public class BookingView extends javax.swing.JFrame {

    private boolean open = false; // flag to see if there is booking panel in use

    /**
     * Creates new form BookingView
     */
    public BookingView(String name) {
        initComponents();
        this.eventNameLabel.setText(name);
        this.setVisible(true);
        open = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addBookingPanel = new javax.swing.JPanel();
        customerNameLabel = new javax.swing.JLabel();
        customerNameField = new javax.swing.JTextField();
        eventSelectLabel = new javax.swing.JLabel();
        customerTypeBox = new javax.swing.JComboBox<>();
        customerTypeLabel = new javax.swing.JLabel();
        seatNoLanel = new javax.swing.JLabel();
        seatNumberBox = new javax.swing.JComboBox<>();
        addBookingButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        eventNameLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        unavailableSeats1 = new javax.swing.JTextArea();
        message = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        customerNameLabel.setText("Customer Name: ");

        eventSelectLabel.setText("Add booking for: ");

        customerTypeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Adult", "Student", "Child", "Senior" }));

        customerTypeLabel.setText("Type: ");

        seatNoLanel.setText("Seat number: ");

        seatNumberBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        seatNumberBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatNumberBoxActionPerformed(evt);
            }
        });

        addBookingButton.setText("Add");

        jLabel1.setText("Unavailable Seats: ");

        eventNameLabel.setText("jLabel2");

        priceLabel.setText("                ");

        unavailableSeats1.setColumns(20);
        unavailableSeats1.setRows(5);
        jScrollPane1.setViewportView(unavailableSeats1);
        unavailableSeats1.setEditable(false);
        unavailableSeats1.setLineWrap(true);
        unavailableSeats1.setOpaque(false);

        message.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        message.setText("        ");

        javax.swing.GroupLayout addBookingPanelLayout = new javax.swing.GroupLayout(addBookingPanel);
        addBookingPanel.setLayout(addBookingPanelLayout);
        addBookingPanelLayout.setHorizontalGroup(
            addBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addBookingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addBookingPanelLayout.createSequentialGroup()
                        .addGroup(addBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(customerNameLabel)
                            .addComponent(customerTypeLabel)
                            .addComponent(seatNoLanel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(addBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(customerTypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seatNumberBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customerNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(95, Short.MAX_VALUE))
                    .addGroup(addBookingPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(message, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(addBookingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(addBookingPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1)
                        .addGap(19, 19, 19))
                    .addGroup(addBookingPanelLayout.createSequentialGroup()
                        .addGroup(addBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addBookingPanelLayout.createSequentialGroup()
                                .addComponent(eventSelectLabel)
                                .addGap(18, 18, 18)
                                .addComponent(eventNameLabel))
                            .addComponent(priceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        addBookingPanelLayout.setVerticalGroup(
            addBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addBookingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eventSelectLabel)
                    .addComponent(eventNameLabel))
                .addGap(30, 30, 30)
                .addGroup(addBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerNameLabel)
                    .addComponent(customerNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerTypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerTypeLabel))
                .addGap(18, 18, 18)
                .addGroup(addBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seatNoLanel)
                    .addComponent(seatNumberBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(priceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(addBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBookingButton)
                    .addComponent(message))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(addBookingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(addBookingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void seatNumberBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatNumberBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatNumberBoxActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        this.open = false;
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBookingButton;
    private javax.swing.JPanel addBookingPanel;
    private javax.swing.JTextField customerNameField;
    private javax.swing.JLabel customerNameLabel;
    private javax.swing.JComboBox<String> customerTypeBox;
    private javax.swing.JLabel customerTypeLabel;
    private javax.swing.JLabel eventNameLabel;
    private javax.swing.JLabel eventSelectLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel message;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JLabel seatNoLanel;
    private javax.swing.JComboBox<String> seatNumberBox;
    private javax.swing.JTextArea unavailableSeats1;
    // End of variables declaration//GEN-END:variables


//get user input and selections
    public String getCustomerName() {
        return this.customerNameField.getText().trim();
    }

    public String getCustomerType() {
        return (String) this.customerTypeBox.getSelectedItem();
    }

    public int getSeatNo() {
        int seatNo = Integer.parseInt(this.seatNumberBox.getSelectedItem().toString());
        return seatNo;
    }

    public void addActionListener(ActionListener Listener) {

        this.addBookingButton.addActionListener(Listener);

    }
    //flag to see if booking panel is in use

    public boolean isOpen() {

        return this.open;
    }
//set error or success message

    public void setMessage(String str) {
        this.message.setText(str);
    }
//display unavailable seats
    public void setSeats(String str) {
        this.unavailableSeats1.setText(str);

    }

    public void setPriceLabel(String str) {
        this.priceLabel.setText(str);
    }



}
